---
- src: git@github.com:nilsonvieira/InstallDocker.git
  scm: git
  name: installDocker

- src: git@github.com:nilsonvieira/InstallK8s.git
  scm: git
  name: installK8s

- src: git@github.com:nilsonvieira/Install_NodeJS.git
  scm: git
  name: installNodeJS