---
- src: git@github.com:nilsonvieira/Ansible-Role-Install-Docker.git
  scm: git
  name: Ansible-Role-Install-Docker

- src: git@github.com:nilsonvieira/Ansible-Role-Install-K8S.git
  scm: git
  name: Ansible-Role-Install-K8S

- src: git@github.com:nilsonvieira/Ansible-Role-Install-NodeJS.git
  scm: git
  name: Ansible-Role-Install-NodeJS

- src: git@github.com:nilsonvieira/Ansible-Role-Install-Themes.git
  scm: git
  name: Ansible-Role-Install-Themes