---
- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "Instalar Pacotes Necessários"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - curl
      - wget
      - remmina
      - flameshot
      - arc-theme
      - papirus-icon-theme
      - google-chrome-stable
