---
- name: "GENERAL PACK: Instalar Pacotes Necessários"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - curl
      - wget
      - remmina
      - flameshot
  tags:
    - buster
    - focal
