---
dependencies: []

galaxy_info:
  role_name: InstallDocker
  author: Nilson R. S. Vieira
  description: instalar o Docker
  license: GPLv2

  platforms:
  - name: Debian
    versions: 
      - buster
  - name: Ubuntu
    versions: 
      - focal
  - name: Mint
    versions: 
      - Ulyana
  - name: Deepin
    versions: 
      - 20.2

